[build]
  command = "tsc && vite build"
  publish = "dist"

[build.environment]
  # Set these in the Netlify UI
  # VITE_SUPABASE_URL = "your_supabase_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key" 